# Generated by Django 3.2 on 2024-06-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_mdbuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdbuser',
            options={'ordering': ('id',)},
        ),
    ]
