# Generated by Django 3.2 on 2024-06-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240614_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdbuser',
            options={'ordering': ('id',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
