# Generated by Django 3.2 on 2024-06-15 09:37

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_mdbuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mdbuser',
            options={'ordering': ('username',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='mdbuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=9, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='mdbuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким юзернеймом уже существует.'}, max_length=150, unique=True, validators=[users.validators.validate_username], verbose_name='Юзернейм'),
        ),
    ]
